'Component: Automatic': ["src/Automatic"]
'Component: Common': ["src/Common"]
'Component: Prefetcher': ["src/LegacyFilter"]
'Component: Security': ["src/Security"]
'Component: Versions': ["src/Versions"]
